/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: string;
  linkColumns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & CtaLink
    >;
    _type: "linkColumn";
    _key: string;
  }>;
  socials?: Array<{
    platform?: "facebook" | "instagram" | "x" | "youtube";
    url?: string;
    _type: "social";
    _key: string;
  }>;
};

export type HelpCenter = {
  _id: string;
  _type: "helpCenter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: {
    heading?: string;
    body?: string;
  };
  faqGroups?: Array<{
    title?: string;
    groupId?: Slug;
    items?: Array<{
      question?: string;
      answer?: string;
      _type: "faqItem";
      _key: string;
    }>;
    _type: "faqGroup";
    _key: string;
  }>;
  policies?: Array<{
    icon?:
      | "truck"
      | "shield-check"
      | "rotate-ccw"
      | "headphones"
      | "lock"
      | "file-text"
      | "mail"
      | "message-circle"
      | "phone"
      | "clock";
    title?: string;
    summary?: string;
    _type: "policy";
    _key: string;
  }>;
  supportChannels?: Array<{
    icon?:
      | "truck"
      | "shield-check"
      | "rotate-ccw"
      | "headphones"
      | "lock"
      | "file-text"
      | "mail"
      | "message-circle"
      | "phone"
      | "clock";
    title?: string;
    description?: string;
    detail?: string;
    _type: "supportChannel";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    heading?: string;
    subheading?: string;
    primaryCta?: CtaLink;
    secondaryCta?: CtaLink;
  };
  promo?: {
    eyebrow?: string;
    heading?: string;
    body?: string;
    cta?: CtaLink;
  };
  trustItems?: Array<{
    icon?:
      | "truck"
      | "shield-check"
      | "rotate-ccw"
      | "headphones"
      | "lock"
      | "file-text"
      | "mail"
      | "message-circle"
      | "phone"
      | "clock";
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CtaLink
  | Footer
  | HelpCenter
  | Slug
  | HomePage
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    description,    "ogImage": ogImage.asset->url  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  ogImage: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    hero{      heading,      subheading,      primaryCta{ label, href },      secondaryCta{ label, href }    },    promo{      eyebrow,      heading,      body,      cta{ label, href }    },    trustItems[]{      _key,      icon,      title,      description    }  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    heading: string | null;
    subheading: string | null;
    primaryCta: {
      label: string | null;
      href: string | null;
    } | null;
    secondaryCta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  promo: {
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  trustItems: Array<{
    _key: string;
    icon:
      | "clock"
      | "file-text"
      | "headphones"
      | "lock"
      | "mail"
      | "message-circle"
      | "phone"
      | "rotate-ccw"
      | "shield-check"
      | "truck"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: HELP_CENTER_QUERY
// Query: *[_type == "helpCenter"][0]{    intro{ heading, body },    faqGroups[]{      _key,      title,      "groupId": groupId.current,      items[]{ _key, question, answer }    },    policies[]{ _key, icon, title, summary },    supportChannels[]{ _key, icon, title, description, detail }  }
export type HELP_CENTER_QUERY_RESULT = {
  intro: {
    heading: string | null;
    body: string | null;
  } | null;
  faqGroups: Array<{
    _key: string;
    title: string | null;
    groupId: string | null;
    items: Array<{
      _key: string;
      question: string | null;
      answer: string | null;
    }> | null;
  }> | null;
  policies: Array<{
    _key: string;
    icon:
      | "clock"
      | "file-text"
      | "headphones"
      | "lock"
      | "mail"
      | "message-circle"
      | "phone"
      | "rotate-ccw"
      | "shield-check"
      | "truck"
      | null;
    title: string | null;
    summary: string | null;
  }> | null;
  supportChannels: Array<{
    _key: string;
    icon:
      | "clock"
      | "file-text"
      | "headphones"
      | "lock"
      | "mail"
      | "message-circle"
      | "phone"
      | "rotate-ccw"
      | "shield-check"
      | "truck"
      | null;
    title: string | null;
    description: string | null;
    detail: string | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{    tagline,    linkColumns[]{      _key,      title,      links[]{ _key, label, href }    },    socials[]{ _key, platform, url }  }
export type FOOTER_QUERY_RESULT = {
  tagline: string | null;
  linkColumns: Array<{
    _key: string;
    title: string | null;
    links: Array<{
      _key: string;
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  socials: Array<{
    _key: string;
    platform: "facebook" | "instagram" | "x" | "youtube" | null;
    url: string | null;
  }> | null;
} | null;
